
version: "3.4"

services:
  php:
    image: webdevops/php-nginx-dev:8.2-alpine
    depends_on:
      - db
    volumes:
      - ./api:/app
    environment:
      DATABASE_URL: mysql://user:password@db:3306/comments?serverVersion=8&charset=utf8mb4
      WEB_DOCUMENT_ROOT: /app/public
    ports:
      - "8111:80"

  db:
    image: mysql:8
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=user
      - MYSQL_DATABASE=comments
      - MYSQL_PASSWORD=password
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3327:3306"


volumes:
  db_data:
